---
title: "Group Project"
---

# Introduction

## Executive Summary

In a group of 3-4 statisticians, you will be creating a report about a data set for a Permanent Party Squadron Commander (PPSC). Your final report will state a data-driven conclusion about the data set your group presents. You will work on three individual and four group assignments throughout the semester.

You will be assigned into groups based on the inputs in your Group Preferences Form (submitted on Gradescope by Lesson 03).

## Group Project Learning Objectives

1.  Identify meaningful research questions that can be investigated using an existing dataset.

2.  Perform exploratory data analysis using data wrangling, numerical summaries, and a variety of data visualizations appropriate for a selected dataset.

3.  Select and apply an appropriate statistical method (hypothesis testing or linear regression) to answer a research question and support a data-driven recommendation.

4.  Communicate statistical findings effectively through a professional report that is organized, visually engaging, and understandable to a non-statistical audience.

5.  Collaborate effectively as a project team by leveraging individual strengths, incorporating feedback from peers, mentors, and instructors, and contributing to a shared final product.

## Checkpoints

There are several project checkpoints throughout the semester. These checkpoints are designed to help you complete the project successfully without a huge, last-minute effort at the end of the term. There are both group and individual checkpoints, outlined below:

+--------------------------------------------------------------------------------------------------------+--------------------------+--------------+
| Task Type and Topic                                                                                    | Due Date                 | Leader Task? |
+========================================================================================================+==========================+==============+
| Individual Task #1 - Finding Data                                                                      | T6\                      | No           |
|                                                                                                        | (21 August)              |              |
+--------------------------------------------------------------------------------------------------------+--------------------------+--------------+
| Group Task #1 - Establishing Group Norms                                                               | T10\                     | Yes          |
|                                                                                                        | (02 September)           |              |
+--------------------------------------------------------------------------------------------------------+--------------------------+--------------+
| Individual Task #2 - Data Wrangling and Exploration                                                    | T14\                     | Yes          |
|                                                                                                        | (16 September)           |              |
+--------------------------------------------------------------------------------------------------------+--------------------------+--------------+
| Group Task #2 - Exploratory Data Analysis (includes choosing a research question, dataset, and mentor) | T20\                     | Yes          |
|                                                                                                        | (05 October)             |              |
+--------------------------------------------------------------------------------------------------------+--------------------------+--------------+
| Project Feedback Day (in-class)                                                                        | M26/T26\                 | No           |
|                                                                                                        | (21/22 October)          |              |
+--------------------------------------------------------------------------------------------------------+--------------------------+--------------+
| Individual Task #3 - Revising the Exploration                                                          | T29\                     | Yes          |
|                                                                                                        | (30 Otober)              |              |
+--------------------------------------------------------------------------------------------------------+--------------------------+--------------+
| Group Task #3 - Proposing a Data Task                                                                  | T33\                     | Yes          |
|                                                                                                        | (12 November)            |              |
+--------------------------------------------------------------------------------------------------------+--------------------------+--------------+
| Project Work Day (in-class)                                                                            | M37/T37 (23/24 November) | No           |
+--------------------------------------------------------------------------------------------------------+--------------------------+--------------+
| Group Task #4 - Final Submission                                                                       | T39\                     | No           |
|                                                                                                        | (04 December)            |              |
+--------------------------------------------------------------------------------------------------------+--------------------------+--------------+

### Leader tasks

Five of the seven assignments have "Leader tasks" associated with them. **Your group must complete all five leader tasks.** Each statistician in your group must be the leader at least once and no one can be the leader more than twice. As part of Group Task #1, your group will create a leader schedule to ensure that you meet these conditions and so that everyone knows who will be leading when.

### Mentor Feedback

As part of Group Task #2, groups will select at least one mentor with a military background from whom they will solicit feedback on the mid-term project submission (Group Task #2). The mentor will be asked to provide feedback on the professionalism, formatting, and communication of the mid-term submission using a provided rubric. The mentor should be a non-statistician and can be one of the group member's PPSCs or AMTs, a faculty member, an OIC or OR, or even a sponsor.

### Grading

There are three standards corresponding to the group project:

1.  Group submission (Group Task #2 and Group Task #4)

2.  Individual submissions and effort on group tasks, based on final report and individual task completion (including at least one leader task) and group member evaluations

3.  Peer feedback, based on the quality of feedback you offer your group members on the in-class Peer Feedback Day (Lesson 26)

### Using templates

You will need to use many templates as future officers in the Air Force or Space Force, so we are explicitly including correct use of templates as part of the tasks throughout the project. Correctly using the template is part of each assignment and will contribute to your achievement of the group project standards.
