---
title: "Course Schedule"
---

This page includes the course schedule for the Fall 2026 semester, along with all the assigned readings and graded events.

::: {.callout-note collapse="true"}
## Accessing the Assigned Readings

The assigned readings can be accessed via the links below or in the Course Letter.

*OpenIntro Statistics* and *Introduction to Modern Statistics* are both available as a free e-book. The readings for this course will come from four digitally available textbooks, from the links in the course letter, also provided below:

-   **David Diez,** **Mine Cetinkaya-Rundel, and Christopher D. Barr.** OpenIntro Statistics, 4^th^ Edition. Free PDF available at [https://openintro.org/book/os/.](https://openintro.org/book/os/){target="_blank"}

-   **Mine Cetinkaya-Rundel and Johanna Hardin**. *Introduction to Modern Statistics*, 2^nd^ Edition. Free web-native version available at [https://www.openintro-ims.netlify.app](https://www.openintro-ims.netlify.app){.uri target="_blank"} (may not work on MissionNet).

-   **Chester Ismay, Albert Y. Kim, and Arturo Valdivia**. *Modern Dive (v2).* Free e-book available at [https://moderndive.com/v2/](https://moderndive.com/v2/){.uri target="_blank"}.

-   **Bradley Warner, Brianna Hitt, and Ken Horton**. *Computational Probability and Statistics*. Free e-book available at [https://ds-usafa.github.io/Quarto-Book/](https://ds-usafa.github.io/Quarto-Book/){.uri target="_blank"}.
:::

::: {.callout-tip collapse="true" icon="false"}
## Fall Calendar with Course Assignments

To view the graded events for this course, overlaid on the Fall 2026 academic calendar, click [here](DS220_Fall2026_Calendar.pdf){target="_blank"}.
:::

 

## Block 1: Probability Models

+--------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------+
| Lesson | Topic                                   | BEFORE Class                                                                                                                                                                                                                                            | Graded Events (due dates)       |
+========+=========================================+=========================================================================================================================================================================================================================================================+=================================+
| 1      | Intro to Data Science and Generative AI | -   [Practice Notebook for Lesson 1](https://notebook.google.com/notebook/6a7fdd3b-38a3-48c7-91df-5603bfd2a629){target="_blank"}                                                                                                                        |                                 |
+--------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------+
| 2      | Intro to Probability                    | -   READ:                                                                                                                                                                                                                                               |                                 |
|        |                                         |                                                                                                                                                                                                                                                         |                                 |
|        |                                         |     -   Section 3.1 Defining Probability, *OpenIntro Statistics*                                                                                                                                                                                        |                                 |
|        |                                         |                                                                                                                                                                                                                                                         |                                 |
|        |                                         | -   [Reading Guide for Lesson 2](https://notebooklm.google.com/notebook/3233b224-a086-4aeb-8bb5-1412444f7ee9){target="_blank"}                                                                                                                          |                                 |
|        |                                         |                                                                                                                                                                                                                                                         |                                 |
|        |                                         | -   Submit Reading Guide on Gradescope                                                                                                                                                                                                                  |                                 |
+--------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------+
| 3      | Conditional Probability, Bayes' Rule    | -   READ:                                                                                                                                                                                                                                               | -   Pre-course AI Questionnaire |
|        |                                         |                                                                                                                                                                                                                                                         | -   Group Preferences Form      |
|        |                                         |     -   Section 3.2 Conditional Probability, *OpenIntro Statistics*                                                                                                                                                                                     |                                 |
|        |                                         |                                                                                                                                                                                                                                                         |                                 |
|        |                                         | -   [Reading Guide for Lesson 3](https://notebooklm.google.com/notebook/06a6c546-6916-40cb-a710-a469f0842121){target="_blank"}                                                                                                                          |                                 |
|        |                                         |                                                                                                                                                                                                                                                         |                                 |
|        |                                         | -   Submit Reading Guide on Gradescope                                                                                                                                                                                                                  |                                 |
+--------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------+
| 4      | Discrete Random Variables               | -   READ:                                                                                                                                                                                                                                               | -   HW1 Concept Check           |
|        |                                         |                                                                                                                                                                                                                                                         | -   HW1 Core Competencies       |
|        |                                         |     -   [Section 10.2 Random variables (Intro through 10.2.4)](https://ds-usafa.github.io/Quarto-Book/Discrete-Random-Variables.html){target="_blank"}, *Computational Probability and Statistics*                                                      |                                 |
|        |                                         |                                                                                                                                                                                                                                                         |                                 |
|        |                                         |     -   Section 3.4 (Intro through 3.4.2) Random Variables, *OpenIntro Statistics*                                                                                                                                                                      |                                 |
|        |                                         |                                                                                                                                                                                                                                                         |                                 |
|        |                                         | -   [Reading Guide for Lesson 4](https://notebooklm.google.com/notebook/08abf03d-1d2d-4f78-9447-7c1d115dbf69){target="_blank"}                                                                                                                          |                                 |
|        |                                         |                                                                                                                                                                                                                                                         |                                 |
|        |                                         | -   Submit Reading Guide on Gradescope                                                                                                                                                                                                                  |                                 |
+--------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------+
| 5      | Continuous Random Variables             | -   READ:                                                                                                                                                                                                                                               |                                 |
|        |                                         |                                                                                                                                                                                                                                                         |                                 |
|        |                                         |     -   [Section 11.2 Continuous random variables (Intro through 11.2.2) and 11.3 Moments](https://ds-usafa.github.io/Quarto-Book/Continuous-Random-Variables.html){target="_blank"}, *Computational Probability and Statistics*                        |                                 |
|        |                                         |                                                                                                                                                                                                                                                         |                                 |
|        |                                         |     -   Section 3.5 Continuous distributions, *OpenIntro Statistics*                                                                                                                                                                                    |                                 |
|        |                                         |                                                                                                                                                                                                                                                         |                                 |
|        |                                         | -   [Reading Guide for Lesson 5](https://notebooklm.google.com/notebook/c18d08c7-f192-4790-96ec-fd32137e30e8){target="_blank"}                                                                                                                          |                                 |
|        |                                         |                                                                                                                                                                                                                                                         |                                 |
|        |                                         | -   Submit Reading Guide on Gradescope                                                                                                                                                                                                                  |                                 |
+--------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------+
| 6      | Discrete Named Distributions            | -   READ: Sections 4.2 Geometric distribution, 4.3 Binomial distribution (through 4.3.1), and 4.5 Poisson distribution, *OpenIntro Statistics*                                                                                                          | -   Project Individual Task #1  |
|        |                                         |                                                                                                                                                                                                                                                         |                                 |
|        |                                         | -   [Reading Guide for Lesson 6](https://notebooklm.google.com/notebook/5aeb5c88-de9a-435b-b93f-4d3a6481e74c){target="_blank"}                                                                                                                          |                                 |
|        |                                         |                                                                                                                                                                                                                                                         |                                 |
|        |                                         | -   Submit Reading Guide on Gradescope                                                                                                                                                                                                                  |                                 |
+--------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------+
| 7      | Continuous Named Distributions          | -   READ:                                                                                                                                                                                                                                               | -   HW2 Concept Check           |
|        |                                         |                                                                                                                                                                                                                                                         | -   HW2 Core Competencies       |
|        |                                         |     -   Section 4.1 Normal Distribution, *OpenIntro Statistics*                                                                                                                                                                                         |                                 |
|        |                                         |                                                                                                                                                                                                                                                         |                                 |
|        |                                         |     -   [Section 13.2.1 Uniform distribution and 13.2.2 Exponential distribution](https://ds-usafa.github.io/Quarto-Book/Named-Continuous-Distributions.html#exponential-distribution){target="_blank"} from *Computational Probability and Statistics* |                                 |
|        |                                         |                                                                                                                                                                                                                                                         |                                 |
|        |                                         | -   [Reading Guide for Lesson 7](https://notebooklm.google.com/notebook/3e74f22c-0af6-4afe-b5e7-d771b0a01990){target="_blank"}                                                                                                                          |                                 |
|        |                                         |                                                                                                                                                                                                                                                         |                                 |
|        |                                         | -   Submit Reading Guide on Gradescope                                                                                                                                                                                                                  |                                 |
+--------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------+

 

## Block 2: Understanding Data

+--------+-----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------+
| Lesson | Topic                       | BEFORE Class                                                                                                                                                                                                                                          | Graded Events (due dates) |
+========+=============================+=======================================================================================================================================================================================================================================================+===========================+
| 8      | Data Basics                 | -   READ:                                                                                                                                                                                                                                             |                           |
|        |                             |                                                                                                                                                                                                                                                       |                           |
|        |                             |     -   Chapter 1 Hello data from *Introduction to Modern Stats* *(2e)*                                                                                                                                                                               |                           |
|        |                             |                                                                                                                                                                                                                                                       |                           |
|        |                             |     -   Chapter 5 Exploring numerical data from *Introduction to Modern Stats* *(2e)*                                                                                                                                                                 |                           |
|        |                             |                                                                                                                                                                                                                                                       |                           |
|        |                             |     -   ***Note: You may not be able to access the web-native version of Intro to Modern Stats (2nd edition) on MissionNet WiFi. Please use the provided PDF of the textbook (in Teams) or refer to the PDF of the assigned reading in NotebookLM.*** |                           |
|        |                             |                                                                                                                                                                                                                                                       |                           |
|        |                             | -   [Reading Guide for Lesson 8](https://notebooklm.google.com/notebook/6f92eaad-f39d-44fa-802a-fc4496e533ea){target="_blank"}                                                                                                                        |                           |
|        |                             |                                                                                                                                                                                                                                                       |                           |
|        |                             | -   Submit Reading Guide on Gradescope                                                                                                                                                                                                                |                           |
+--------+-----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------+
| 9      | GR1                         | Study! Practice!                                                                                                                                                                                                                                      |                           |
|        |                             |                                                                                                                                                                                                                                                       |                           |
|        |                             | -   [**Block 1 NotebookLM Study Guide**](https://notebook.google.com/notebook/8187bc92-1afc-472d-8448-d1c29558174b){target="_blank"}                                                                                                                  |                           |
|        |                             | -   GR1 will take place on Friday 28 August (M9) during the common GR time, starting at 0630                                                                                                                                                          |                           |
|        |                             | -   There will be no regular class on M9/T9                                                                                                                                                                                                           |                           |
+--------+-----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------+
| 10     | Data Collection and Studies | -   READ:                                                                                                                                                                                                                                             | -   Project Group Task #1 |
|        |                             |                                                                                                                                                                                                                                                       |                           |
|        |                             |     -   Chapter 2 Study design from *Introduction to Modern Stats (2e)*                                                                                                                                                                               |                           |
|        |                             |                                                                                                                                                                                                                                                       |                           |
|        |                             | -   [Reading Guide for Lesson 10](https://notebooklm.google.com/notebook/725f1277-edc9-4935-800d-01e8d6eb4b25){target="_blank"}                                                                                                                       |                           |
|        |                             |                                                                                                                                                                                                                                                       |                           |
|        |                             | -   Submit Reading Guide on Gradescope                                                                                                                                                                                                                |                           |
+--------+-----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------+
| 11     | Tidy Data                   | -   READ:                                                                                                                                                                                                                                             |                           |
|        |                             |                                                                                                                                                                                                                                                       |                           |
|        |                             |     -   [Chapter 4 Data Importing and Tidy Data](https://moderndive.com/v2/tidy.html) from *Modern Dive*                                                                                                                                              |                           |
|        |                             |                                                                                                                                                                                                                                                       |                           |
|        |                             | -   [Reading Guide for Lesson 11](https://notebooklm.google.com/notebook/c15d1e56-d2a1-42f9-9cc3-174b52c7ebe6){target="_blank"}                                                                                                                       |                           |
|        |                             |                                                                                                                                                                                                                                                       |                           |
|        |                             | -   Submit Reading Guide on Gradescope                                                                                                                                                                                                                |                           |
+--------+-----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------+
| 12     | Data Wrangling              | -   READ:                                                                                                                                                                                                                                             | -   HW3 Concept Check     |
|        |                             |                                                                                                                                                                                                                                                       | -   HW3 Core Competencies |
|        |                             |     -   [Chapter 3 Data Wrangling](https://moderndive.com/v2/wrangling.html){target="_blank"} from *Modern Dive*                                                                                                                                      |                           |
|        |                             |                                                                                                                                                                                                                                                       |                           |
|        |                             | -   [Reading Guide for Lesson 12](https://notebooklm.google.com/notebook/f3226153-1b7b-4766-af0f-bd472099e7fb){target="_blank"}                                                                                                                       |                           |
|        |                             |                                                                                                                                                                                                                                                       |                           |
|        |                             | -   Submit Reading Guide on Gradescope                                                                                                                                                                                                                |                           |
+--------+-----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------+

 

## Block 3: Statistical Inference

 

## Block 4: Linear Regression and the Central Limit Theorem
